project_id = "lergmodntwjeyljgzdsh"

[functions.ai-analytics]
verify_jwt = true

[functions.create-stripe-connect-account]
verify_jwt = true

[functions.create-stripe-connect-link]
verify_jwt = true

[functions.create-checkout]
verify_jwt = false

[functions.create-free-reservation]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.send-ticket-email]
verify_jwt = false

[functions.create-group-order]
verify_jwt = true

[functions.pay-group-share]
verify_jwt = false

[functions.generate-flyer]
verify_jwt = true

[functions.get-group-order]
verify_jwt = false

[functions.toggle-ticket-resale]
verify_jwt = true

[functions.check-subscription]
verify_jwt = true

[functions.create-subscription-checkout]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true
