project_id = "lergmodntwjeyljgzdsh"

[functions.ai-analytics]
verify_jwt = true

[functions.create-stripe-connect-account]
verify_jwt = true

[functions.create-stripe-connect-link]
verify_jwt = true

[functions.create-checkout]
verify_jwt = false

[functions.create-free-reservation]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false